version: '3.9'
services:
  app:

    build:
      context: .
      dockerfile: ./docker/Dockerfile
    
    volumes:
      - ./work:/work
      - /work/node_modules

    ports: 
      - "8000:8000"
 
